name: Build-And-Test

on:
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"
      - "!release"
  push:
    branches:
      - "postman-testsuite-ci"

env:
  IMAGE_NAME_DEV: for_testing_image
  IMAGE_NAME_PROD: moritzer-petclinic

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Dev Image for testing purposes
      run: docker build . --file dev.Dockerfile --tag $IMAGE_NAME_DEV
    - name: Run Docker Container
      run: docker run -d --name petclinic -p 9966:9966 $IMAGE_NAME_DEV:latest
    - name: Run Maven unit tests in Docker Directory
      run: docker exec -w /spring-petclinic-rest/ petclinic mvn test
    - name: Setup Node-environment for Postman Tests
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Newman (Postman Headless-Runner)
      run: npm install -g newman
    - name: Run Postman Test Collection
      run: newman run https://www.getpostman.com/collections/aa0611affb8560601a98?apikey=${{secrets.POSTMAN_API_KEY}}
