# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build-And-Test

on:
  push:
    branches: [ develop, ci-cd ]
  pull_request:
    branches: [ develop ]

env:
  IMAGE_NAME: for_testing_image

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . --file dev.Dockerfile --tag $IMAGE_NAME

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Container
        run: docker run -d --name petclinic -p 9966:9966 $IMAGE_NAME:latest
      - name: Run Maven unit tests in Docker Directory
        run: mvn test
